version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/letsencrypt
      - ./logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - proxy-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nginx
    command: renew
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"

networks:
  proxy-network:
    driver: bridge