version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/letsencrypt
      - ./logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot
    restart: unless-stopped
    networks:
      - proxy-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet; sleep 12h & wait $${!}; done;'"
    restart: unless-stopped
    networks:
      - proxy-network
      
  mock-twilio:
    image: python:3.9-alpine
    container_name: mock-twilio
    ports:
      - "3000:3000"
    volumes:
      - ./mock-twilio:/app
    working_dir: /app
    command: >
      sh -c "pip install --no-cache-dir flask==2.0.1 werkzeug==2.0.3 markupsafe==2.0.1 jinja2==3.0.3 itsdangerous==2.0.1 click==8.0.4 && 
      python app.py"
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge